export const Rotas  = {
    Home: '/',
    Chaves: '/Chaves',
    ChavesNew: '/Chaves/Cadastro',
    ChavesCopia: '/Chaves/Copias',
    ChavesDescarte: '/Chaves/Descarte',
    ChavesEstoqueAtualizar: '/Chaves/Estoque/Atualizar',
    ChavesEstoquePedido: '/Chaves/Estoque/Pedido',
    ChavesEstoqueHistorico: '/Chaves/Estoque/Historico',
    Alicates: '/Alicates',
    AlicatesNew: '/Alicates/Cadastro',
    AlicatesHistorico: '/Alicates/Historico',
    Servico: '/Servico',
    ServicoNew: '/Servico/Cadastro',
    ServicoHistorico: '/Servico/Historico',
    EstatisticasChave: '/Estatistica/Chaves',
    EstatisticasAlicates: '/Estatistica/Alicates',
    EstatisticasServicos: '/Estatistica/Servicos',
}