export const Rotas  = {
    Home: '/',
    Chaves: '/Chaves',
    ChavesNew: '/Chaves/Cadastro',
    ChavesVenda: '/Chaves/Venda',
    ChavesEstoqueAtualizar: '/Chaves/Estoque/Atualizar',
    ChavesEstoquePedido: '/Chaves/Estoque/Pedido',
    ChavesEstoqueHistorico: '/Chaves/Estoque/Historico',
    Alicates: '/Alicates',
    AlicatesNew: '/Alicates/Cadastro',
    AlicatesHistorico: '/Alicates/Historico',
    Servico: '/Servico',
    ServicoNew: '/Servico/Cadastro',
    ServicoHistorico: '/Servico/Historico',
}