export const Rotas = {
    Home: '/',
    Chaves: '/Chaves',
    ChavesCadastro: '/Chaves/Cadastro',
    ChavesEstoqueAtualizar: '/Chaves/Estoque/Atualizar',
    ChavesEstoquePedido: '/Chaves/Estoque/Pedido',
    ChavesEstoqueHistorico: '/Chaves/Estoque/Historico',
    AmolacaoCadastro: '/Amolacao/Cadastro',
    AmolacaoEstoque: '/Amolacao/Estoque',
    Servico: '/Servico',
    ServicoNew: '/Servico/Cadastro',
    Relatorios: '/Relatorios',
    EstatisticasChave: '/Estatistica/Chaves',
    EstatisticasAlicates: '/Estatistica/Alicates',
    EstatisticasServicos: '/Estatistica/Servicos',
}